Добавлены задачи 3.1-5
js-tasks-ru/jsbasic-20221215_rstrunin383 pull request #6
Opened 2023-01-05 19:39 UTC by rstrunin

2023-01-05 19:40 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-01-06 16:06 UTC, koalex requested changes
Исправить замечание в **3-5**

2023-01-06 16:06 UTC, koalex commented on 3-module/5-task/index.js
> +  return {'min' : compared[0],
Кавычки не обязательно.
На занятии я говорил, что задачу нужно решить используя [Math.min](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/min) и [Math.max](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/max) (нужно исправить)

2023-01-06 18:52 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-01-06 18:53 UTC, rstrunin commented
Исправил задачу 3.5, использованием методов Math

2023-01-09 08:29 UTC, koalex approved these changes

2023-01-09 08:30 UTC, merged