Добавлена задача 5.1
js-tasks-ru/jsbasic-20221215_rstrunin383 pull request #8
Opened 2023-01-13 12:07 UTC by rstrunin

2023-01-13 12:07 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-01-13 12:50 UTC, koalex requested changes
Несмотря на то, что тесты ОК надо исправить замечание в **5-1**

2023-01-13 12:50 UTC, koalex commented on 5-module/1-task/index.js
> +    element.hidden = 'true';
**true** надо без кавычек, вот так:
`element.hidden = true;`

2023-01-17 14:37 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-01-17 14:55 UTC, koalex approved these changes

2023-01-17 14:55 UTC, merged